Repository gladiusio/gladius-masternode, pull requests merged in 2019-02, with the labels that each got.

#20 Merging new changes to master
  .gitignore
  README.md
  src/MasternodeConfig.h
  src/MasternodeServer.cpp
  src/NetworkState.cpp
  src/tests/MasternodeTests.cpp
Labels: cla-signed

#21 Added documentation, env file config, and unit test fixes
  Dockerfile
  README.md
  env.list.sample
  src/MasternodeConfig.h
  src/MasternodeServer.cpp
  src/NetworkState.cpp
  src/NetworkState.h
  src/tests/MasternodeTests.cpp
Labels: cla-signed

#22 Add support for pool domain
  README.md
  env.list.sample
  src/MasternodeConfig.h
  src/MasternodeServer.cpp
  src/NetworkState.cpp
  src/NetworkState.h
  src/tests/Makefile.am
  src/tests/MasternodeTests.cpp
  src/tests/NetworkStateTests.cpp
  src/tests/TestRunner.cpp
  src/tests/TestUtils.h
Labels: cla-signed

#23 Fix missing body
  src/ProxyHandler.cpp
  src/ServiceWorker.cpp
Labels: bug, cla-signed

#24 Fix missing domain
  Dockerfile
  src/MasternodeServer.cpp
  src/NetworkState.cpp
  src/tests/NetworkStateTests.cpp
Labels: cla-signed

#26 Code cleanup day results
  Dockerfile
  src/Cache.cpp
  src/Cache.h
  src/Makefile.am
  src/Masternode.cpp
  src/Masternode.h
  src/NetworkState.cpp
  src/NetworkState.h
  src/RedirectHandler.h
  src/Router.cpp
  src/Router.h
  src/ServiceWorker.h
  src/tests/Makefile.am
Labels: cla-signed, enhancement

#25 Adds dns connector to the master node
  deploy-compose.yml
Labels: cla-signed
